# Generated by Django 6.0.8 on 2026-09-17 13:47

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeferredOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_label", models.CharField(max_length=100)),
                ("migration_name", models.CharField(max_length=255)),
                ("operation_index", models.PositiveIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("kind", models.CharField(choices=[("drop_column", "Drop column"), ("drop_table", "Drop table"), ("drop_trigger", "Drop trigger and function")], max_length=20)),
                ("table_name", models.CharField(max_length=255)),
                ("column_name", models.CharField(blank=True, max_length=255)),
                ("sql", models.TextField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("done", "Done"), ("failed", "Failed"), ("skipped", "Skipped")], default="pending", max_length=10)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("resolution_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("app_label", "migration_name", "operation_index", "sequence"), name="deferred_migrations_unique_statement")],
            },
        ),
    ]
