# Generated by Django 6.0.8 on 2026-09-18 13:50

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("deferred_migrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRename",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_label", models.CharField(max_length=100)),
                ("old_model", models.CharField(max_length=100)),
                ("new_model", models.CharField(max_length=100)),
                ("rewritten_operation_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="deferredoperation",
            name="kind",
            field=models.CharField(choices=[("drop_column", "Drop column"), ("drop_table", "Drop table"), ("drop_trigger", "Drop trigger and function"), ("drop_view", "Drop compatibility view")], max_length=20),
        ),
    ]
